### PR TITLE
For ODFE 1.12 release

### PR DESCRIPTION
**Pull request by zhyuanqi**
**Description**

Bump up security kibana plugin version to 1.12.  Targeting kibana 7.10
File change in kibana.json, package.json

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by yuxitang-amzn** [comment]
Please describe the purpose of the change like "Bump up version to 1.12, targeting kibana 7.10"

**Review by bandinib-amzn — COMMENTED** [review]
Could you please add the result of unit test in the description?

- Unit test command: `yarn test:jest_ui --coverage `

**Comment by zhyuanqi** [comment]
> Please describe the purpose of the change like "Bump up version to 1.12, targeting kibana 7.10"

Did it. Thank you

**Comment by yuxitang-amzn** [comment]
I believe there is a disclaimer "By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice." in the PR description template, please keep it.

**Review by yuxitang-amzn — APPROVED** [review]

**Comment by zhyuanqi** [comment]
> Could you please add the result of unit test in the description?
> 
> * Unit test command: `yarn test:jest_ui --coverage `

Would apply unit test when the backend plugin is ready.

**Pull request merged**
